language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - tools
    - build-tools-30.0.3
    - android-30
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
script: ./gradlew build
